ticket/Ticket/urls.py
from django.urls import path
from .import views


app_name='Ticket'

urlpatterns = [
    path('<int:user_id>', views.tickets ,name='tickets'),
    path('add_ticket/<int:user_id>/',views.add_ticket,name='add_ticket'),
    path('<int:year>-<int:month>-<int:day>/<slug:slug>/',views.detail_ticket,name='detail_ticket'),
    path('add_reply/<int:tickets_id>/<int:comment_id>',views.add_reply,name='add_reply'),
    
]

ticket/account/urls.py
from django.urls import path
from . import views


app_name='account'
urlpatterns = [
    path('login/',views.user_login,name='login'),
    path('register/' , views.user_register , name='register'),
    path('logout/' , views.user_logout, name='logout'),
    path('dashboard/<int:user_id>/', views.user_dashboard,name='dashboard'),
    path('profile/<int:user_id>/',views.user_profile,name='profile'),
]

ticket/ticket/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='account')),
    path('ticket/',include('Ticket.urls',namespace='Ticket')),
]

ticket/templates/inc/messages.html
{% if messages %}
    {% for message in messages %}
        <p class="alert alert-{{ message.tags}} m-2 p-3 ">{{ message }}</p>
    {% endfor %}

{% endif%}

ticket/templates/inc/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="navbar-nav">
        <a class="nav-link active" href="{% url 'account:login' %}">Home</a>
        {% if request.user.is_authenticated %}
        <a class="nav-link active" href="{% url 'account:logout' %}">Logout</a>
        {% else %}
        <a class="nav-link active" href="{% url 'account:login' %}">Login</a>
        <a class="nav-link active" href="{% url 'account:register' %}">Register</a>
        {% endif %}
    </div>
</nav>