ticket/Ticket/urls.py
from django.urls import path
from .import views


app_name='Ticket'

urlpatterns = [
    path('<int:user_id>', views.tickets ,name='tickets'),
    path('add_ticket/<int:user_id>/',views.add_ticket,name='add_ticket'),
    path('<int:year>-<int:month>-<int:day>/<slug:slug>/',views.detail_ticket,name='detail_ticket'),
    path('add_reply/<int:tickets_id>/<int:comment_id>',views.add_reply,name='add_reply'),
    
]

ticket/account/urls.py
from django.urls import path
from . import views


app_name='account'
urlpatterns = [
    path('login/',views.user_login,name='login'),
    path('register/' , views.user_register , name='register'),
    path('logout/' , views.user_logout, name='logout'),
    path('dashboard/<int:user_id>/', views.user_dashboard,name='dashboard'),
    path('profile/<int:user_id>/',views.user_profile,name='profile'),
]

ticket/ticket/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='account')),
    path('ticket/',include('Ticket.urls',namespace='Ticket')),
]

ticket/Ticket/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.deletion import CASCADE
from django.urls import reverse

class ticket(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE,related_name='userr' )
    title=models.CharField(max_length=20)
    ticketID=models.IntegerField()
    slug = models.SlugField(max_length = 50)
    status=models.TextField(max_length=500)
    date=models.DateTimeField(auto_now_add=True)
    receiverID=models.ForeignKey(User,on_delete=models.CASCADE)
    
    def __str__(self):
        return f'{self.user} - {self.status[:30]}'
    
    def get_absolute_url(self):
        return reverse('Ticket:detail_ticket', args=[self.date.year, self.date.month, self.date.day, self.slug])
    
    
    
class Comment(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE,related_name='ucomment')
    ticket=models.ForeignKey(ticket,on_delete=models.CASCADE,related_name='tcomment')
    reply=models.ForeignKey('self',on_delete=models.CASCADE,null=True,blank=True,related_name='rcomment')
    is_reply=models.BooleanField(default=False)
    body=models.TextField(max_length=300)
    created=models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f'{self.user} - {self.body[:30]}'
    class Meta:
        ordering = ('created',)
    
    

ticket/Ticket/forms.py
from django import forms
from django.db.models import fields
from django.forms import widgets
from.models import ticket,Comment

class AddTicketForm(forms.ModelForm):
    class Meta:
        model = ticket
        exclude = ("user","slug")
        
        
class AddCommentForm(forms.ModelForm):
    class Meta:
        model=Comment
        fields=('body',)
        widgets={
            'body' : forms.Textarea(attrs={"class":"form-control"})
        }

class AddReplyForm(forms.ModelForm):
    class Meta:
        model=Comment
        fields=('body',)
        widgets={
            'body' : forms.Textarea(attrs={"class":"form-control"})
        }

ticket/Ticket/views.py
from django.contrib.messages.api import success
from django.shortcuts import get_object_or_404, redirect, render
from .models import ticket,Comment
from .forms import AddCommentForm, AddReplyForm, AddTicketForm
from django.contrib import messages
from django.utils.text import slugify
from django.contrib.auth.models import User
from django.contrib.messages.views import SuccessMessageMixin

def tickets(request,user_id):
    ticket_item= ticket.objects.filter(user_id=user_id)
    return render (request,'ticket/ticket.html',{'ticket_item':ticket_item})


def detail_ticket(request,year,month,day,slug):
    tickets=get_object_or_404(ticket,date__year=year,date__month=month,date__day=day,slug=slug)
    comments=Comment.objects.filter(ticket=tickets ,is_reply=False)
    reply_form = AddReplyForm()
    if request.method == 'POST':
        form=AddCommentForm(request.POST)
        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.ticket = tickets
            new_comment.user = request.user
            new_comment.save()
            messages.success(request,'your comment submitted',success)
            form=AddCommentForm()
    else:
        form=AddCommentForm()
    return render (request,'ticket/detail_ticket.html',{'tickets':tickets, 'comments':comments ,'form':form, 'reply':reply_form})


def add_ticket(request,user_id):
    if request.method == 'POST':
        form = AddTicketForm(request.POST)
        if form.is_valid():
            new_ticket = form.save(commit = False)
            new_ticket.user = request.user
            new_ticket.slug = slugify(form.cleaned_data['title'][:3])
            new_ticket.save()
            return redirect("account:dashboard",user_id)
    else:
        form = AddTicketForm()
    return render(request,'ticket/add_ticket.html',{'form':form})


def add_reply(request,tickets_id,comment_id):
    tickets=get_object_or_404(ticket,id=tickets_id)
    comment=get_object_or_404(Comment,pk=comment_id)
    if request.method == 'POST':
        form = AddReplyForm(request.POST)
        if form.is_valid():
            reply=form.save(commit=False)
            reply.user = request.user
            reply.ticket = tickets
            reply.reply = comment
            reply.is_reply = True
            reply.save()
            messages.success(request,'your reply submitted',"success" )
        return redirect('Ticket:detail_ticket',tickets.date.year,tickets.date.month,tickets.date.day,tickets.slug)

ticket/Ticket/templates/ticket/add_ticket.html
{% extends "base.html" %}

{% block content %}
    <form action="" method="post" class="form-control alert-dark p-4">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Add Ticket">
    </form>
{% endblock %}

ticket/Ticket/templates/ticket/detail_ticket.html
{% extends "base.html" %}

{% block title %}Detail Ticket {% endblock%}
{% block content%}
    <div class="m-2 border-3 border-dark alert-dark p-3">
        <h5 class="text-success">Created :{{tickets.user}} </h5> 
        <small>Date :{{tickets.date|date}}</small> 
        <br><br>
        <h6>Title :{{tickets.title}} | Ticket_ID: {{tickets.ticketID}}</h6>
        <p>Status :{{tickets.status}}</p>
        <p class="text-success">Receiver: {{tickets.receiverID}}</p>
    </div>
    <p class="m-4 text-primary ">This ticket has {{comments.count}} comments</p>
    <br>
    {% if request.user.is_authenticated%}
        <form action="" method="post" class=" m-3">
            {%csrf_token%}
            {{form.as_p}}
            <input type="submit" value="Send" class="btn btn-primary">
            <br><br>
        </form>
    {%else%}
        <p> Not Login</p>
    {%endif%}
    {% for comment in comments%}
        <div class='card bg-dark text-white m-3'>
            <p class='card-header'>{{comment.user}}:</p>
            <p class='card-body'>{{comment.body}}</p>
            <div class="card-body">
                <form action="{% url 'Ticket:add_reply' tickets.id comment.id %}" method="post">
                    {%csrf_token%}
                    {{ reply.as_p}}
                    <input type="submit" value="Reply" class="btn btn-success">
                </form>
            </div>
            {% for reply in comment.rcomment.all %}
                <p class="btn-light p-4 m-5 bg-info">{{reply.user}}: <br> {{reply.body}}</p>
            {% endfor %}
        </div>
        <br>
        {%empty%}
            <br>
            <p class='text-center'> There is no Comment</p>    
    {% endfor%}
{% endblock%}

ticket/Ticket/templates/ticket/ticket.html
{% extends 'base.html' %}
{% block title %} Tickets  {% endblock%}
{% block content %}
<br><br><br>
    {% for item in ticket_item %}
        <div class="card">
            <p class="card-header"> <a href="{% url 'account:dashboard' item.user.id%}">Created by:{{item.user}} | {{item.date|date}}</a> </p>
            <p class="card-body">Status : {{item.status}}</p>
        </div>
    {% endfor %}
{% endblock %}